// import type { Metadata } from "next";
// import "./globals.css";
// import ClientLayout from "@/components/layout/ClientLayout";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="antialiased" suppressHydrationWarning={true}>
//         <ClientLayout>{children}</ClientLayout>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "@/components/layout/ClientLayout";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Donasiin",
  description: "Berbagi kebaikan, ciptakan perubahan.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SessionProvider>
          <ClientLayout>{children}</ClientLayout>
        </SessionProvider>
      </body>
    </html>
  );
}