import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { User, Plus, MessageCircle, House } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="bg-white text-black">
          <nav className="border-b border-b-gray-300 border-bol flex justify-between items-center p-3 pl-8 pr-8">
            <div className="text-2xl font-bold cursor-pointer">Donasiin</div>
            <div className="flex gap-2 items-center cursor-pointer">
              <div>
                <House className="w-5" />
              </div>
              <div className="text-md">Discover</div>
            </div>

            <div className="flex gap-8 items-center cursor-pointer">
              <div className="flex gap-2">
                <div>
                  <MessageCircle className="w-5" />
                </div>
                <div>Messages</div>
              </div>

              <div className="bg-green-800/80 px-2 py-1 rounded-md">
                <div className="flex gap-2 cursor-pointer ">
                  <div className="text-white font-bold">
                    <Plus className="w-4 " />
                  </div>
                  <div className="text-white font-semibold">Share Item</div>
                </div>
              </div>

              <div className="cursor-pointer">
                <User className="w-6" />
              </div>
            </div>
          </nav>
          <section className="min-h-screen">{children}</section>
        </main>
      </body>
    </html>
  );
}
